config/routes.rb
TextHighlighter::Application.routes.draw do
  resources :key_words

  resources :file_uploads

  root :to => 'home#index'

end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base
  attr_accessible :document_text, :file_name, :text_file
  mount_uploader :text_file, DocumentUploader
end

app/models/key_word.rb
class KeyWord < ActiveRecord::Base
  attr_accessible :color_name, :keyword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  # GET /file_uploads
  # GET /file_uploads.json
  def index
    @file_uploads = FileUpload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @file_uploads }
    end
  end

  # GET /file_uploads/1
  # GET /file_uploads/1.json
  def show
    @file_upload = FileUpload.find(params[:id])
    @key_words = KeyWord.last.keyword
    @color = KeyWord.last.color_name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @file_upload }
    end
  end

  # GET /file_uploads/new
  # GET /file_uploads/new.json
  def new
    @file_upload = FileUpload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @file_upload }
    end
  end

  # GET /file_uploads/1/edit
  def edit
    @file_upload = FileUpload.find(params[:id])
  end

  # POST /file_uploads
  # POST /file_uploads.json
  def create
    @file_upload = FileUpload.new(params[:file_upload])
    yomu = Yomu.new(params[:file_upload][:text_file])
    @file_upload.text_file
    @file_upload.document_text = Yomu.new(@file_upload.text_file).text

    respond_to do |format|
      if @file_upload.save
        format.html { redirect_to @file_upload, notice: 'File upload was successfully created.' }
        format.json { render json: @file_upload, status: :created, location: @file_upload }
      else
        format.html { render action: "new" }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /file_uploads/1
  # PUT /file_uploads/1.json
  def update
    @file_upload = FileUpload.find(params[:id])

    respond_to do |format|
      if @file_upload.update_attributes(params[:file_upload])
        format.html { redirect_to @file_upload, notice: 'File upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_uploads/1
  # DELETE /file_uploads/1.json
  def destroy
    @file_upload = FileUpload.find(params[:id])
    @file_upload.destroy

    respond_to do |format|
      format.html { redirect_to file_uploads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/key_words_controller.rb
class KeyWordsController < ApplicationController
  # GET /key_words
  # GET /key_words.json
  def index
    @key_words = KeyWord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @key_words }
    end
  end

  # GET /key_words/1
  # GET /key_words/1.json
  def show
    @key_word = KeyWord.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @key_word }
    end
  end

  # GET /key_words/new
  # GET /key_words/new.json
  def new
    @key_word = KeyWord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @key_word }
    end
  end

  # GET /key_words/1/edit
  def edit
    @key_word = KeyWord.find(params[:id])
  end

  # POST /key_words
  # POST /key_words.json
  def create
    @key_word = KeyWord.new(params[:key_word])

    respond_to do |format|
      if @key_word.save
        format.html { redirect_to @key_word, notice: 'Key word was successfully created.' }
        format.json { render json: @key_word, status: :created, location: @key_word }
      else
        format.html { render action: "new" }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /key_words/1
  # PUT /key_words/1.json
  def update
    @key_word = KeyWord.find(params[:id])

    respond_to do |format|
      if @key_word.update_attributes(params[:key_word])
        format.html { redirect_to @key_word, notice: 'Key word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /key_words/1
  # DELETE /key_words/1.json
  def destroy
    @key_word = KeyWord.find(params[:id])
    @key_word.destroy

    respond_to do |format|
      format.html { redirect_to key_words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/key_words_helper.rb
module KeyWordsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_for(@file_upload, :html => {:multipart => true} ) do |f| %>
  <% if @file_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_upload.errors.count, "error") %> prohibited this file_upload from being saved:</h2>

      <ul>
      <% @file_upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :select_a_file_for_uploading %>
    <%= f.file_field :text_file,placeholder: "Enter the file name" %>
  </div><br/>
  <div class="field">
    <%= f.label :name_of_the_text_file %>
    <%= f.text_field :file_name,placeholder: "Enter the file name"  %>
  </div><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<h1>Editing file_upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_upload,class: "btn" %> --
<%= link_to 'Back', file_uploads_path,class: "btn" %>

app/views/file_uploads/index.html.erb
<h1>Uploaded files</h1>
</br>
<%= link_to 'Upload a new file', new_file_upload_path,class:"btn" %>
</br>
</br>
<div class="table-responsive">
<div class='span11 table-scrollable'>
<table class="table">
  <tr>
    <th>File name</th>
    <th>Text document</th>
    <th></th>
  </tr>

<% @file_uploads.each do |file_upload| %>
  <tr>
    <td><%= file_upload.file_name %></td>
    <td><%= truncate(file_upload.document_text, length: 75) %></td>
    <td><%= link_to 'Show', file_upload,class: "btn" %> <%= link_to 'Edit', edit_file_upload_path(file_upload),class: "btn" %>
    <%= link_to 'Destroy', file_upload, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>
</div>
</div>
<br/>

app/views/file_uploads/new.html.erb
<h1 class="muted">Upload a new file</h1>

<%= render 'form' %>

<%= link_to 'Back', file_uploads_path,class: "btn" %>

app/views/file_uploads/show.html.erb
<style type="text/css">
  .well{
    margin-top: 40px;
  }
#file_name{
  float: right;
}
</style>

<p id="notice"><%= notice %></p>

<p id="file_name">
  <b>File name:</b>
  <%= @file_upload.file_name %>
</p>

<p class="well">
  <b>Document text:</b>
  <%= @file_upload.document_text %>
</p>


<%= link_to 'Edit', edit_file_upload_path(@file_upload),class: "btn" %> --
<%= link_to 'Back', file_uploads_path,class: "btn" %>

<script type="text/javascript">
  var values = "<%= @key_words %>"
  var temp = new Array();
  temp = values.split(",");
  // alert(temp);
  $('body p').highlight(temp);
  $(".highlight").css({ backgroundColor: "#<%= @color %>" });
</script>

app/views/home/index.html.erb
<h1>Welcome !!</h1>

app/views/key_words/_form.html.erb
<%= form_for(@key_word) do |f| %>
  <% if @key_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_word.errors.count, "error") %> prohibited this key_word from being saved:</h2>

      <ul>
      <% @key_word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<style type="text/css">
#key_word_keyword
{
  height:85px;
}
</style>
<h4 class="text-info">Note: Only the last created keywords list will be selected for highlighting.So, try to edit the list and update whenever you have to add new key words.</h4>
  <div class="field" style="height:30%">
    <%= f.label :keywords %>
    <%= f.text_area :keyword,placeholder:"Enter keywords seperated by coma e.g., Hello,Beifall,etc." %>
  </div><br/>
  <div class="field">
    <%= f.label :pick_a_color %>
    <%= f.text_field :color_name,placeholder:"Click here to select a color" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
    $(function() {
      $('#key_word_color_name').wheelColorPicker();
    });
</script>

app/views/key_words/edit.html.erb
<h1>Editing key_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @key_word,class: "btn" %> --
<%= link_to 'Back', key_words_path,class: "btn" %>

app/views/key_words/index.html.erb
<h1>Listing key words</h1>
</br>
<%= link_to 'New Key word', new_key_word_path,class: "btn" %>
</br>
</br>
<div class="table-responsive">
  <div class='span11 table-scrollable'>
    <table class="table">
      <tr>
        <th>Keyword</th>
        <th>Color name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @key_words.each do |key_word| %>
      <tr>
        <td><%= key_word.keyword %></td>
        <td><%= key_word.color_name %></td>
        <td><%= link_to 'Show', key_word,class: "btn" %>
        <%= link_to 'Edit', edit_key_word_path(key_word),class: "btn" %>
        <%= link_to 'Destroy', key_word, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
<br/>

app/views/key_words/new.html.erb
<h1 class="muted">New key words</h1>

<%= render 'form' %>

<%= link_to 'Back', key_words_path,class: "btn" %>

app/views/key_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Keyword:</b>
  <%= @key_word.keyword %>
</p>

<p>
  <b>Color name:</b>
  <%= @key_word.color_name %>
</p>


<%= link_to 'Edit', edit_key_word_path(@key_word),class: "btn" %> --
<%= link_to 'Back', key_words_path,class: "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TextHighlighter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

   

   
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">TextHighlighter</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Search words", key_words_path  %></li>
              <li><%= link_to "Upload files", file_uploads_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%#= bootstrap_flash %>
            <%= yield %>
          </div>
          </div><!--/row-->
      <footer>
      </footer>
    </div> <!-- /container -->
  </body>
</html>